api_key: key1
api_secret: supersecretkeythatlongenough1234567890

ws_url: "ws://localhost:7880"

redis:
  address: localhost:6379

rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090

logging:
  json: false
  level: debug

development: true

rtc_config:
  # udp_port: 7882
  
  use_external_ip: false
  enable_loopback_candidate: true