api_key: key1
api_secret: supersecretkeythatlongenough1234567890
ws_url: ws://172.17.0.1:7880

redis:
  address: 172.17.0.1:6379

rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090

logging:
  json: false
  level: debug

development: true
rtc_config:
    udp_port: 7885
    use_external_ip: false
    enable_loopback_candidate: false
    # node_ip: 172.20.131.38


# cpu_cost:
#   rtmp_cpu_cost: 2.0
#   whip_cpu_cost: 2.0